services:
  redis:
    image: redis:8.0-alpine
    container_name: redis_cache
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - 6379:6379
    volumes:
      - redis-db:/data
    healthcheck:
      test: ["CMD-SHELL", "REDISCLI_AUTH=${REDIS_PASS} redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  redis-db:
    driver: local
